version: '3.8'

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['shared-network']
  environment:
    - DB_TYPE=${N8N_POSTGRES_DB_TYPE}
    - DB_POSTGRESDB_HOST=${N8N_POSTGRES_HOST}
    - DB_POSTGRESDB_USER=${N8N_POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD}
    - DB_POSTGRESDB_DATABASE=${N8N_POSTGRES_DB}
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
  depends_on:
    postgres-n8n:
      condition: service_healthy

services:
  postgres-n8n:
    image: postgres:16-alpine
    networks: ['shared-network']
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${N8N_POSTGRES_USER}
      - POSTGRES_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - POSTGRES_DB=${N8N_POSTGRES_DB}
    volumes:
      - postgres_n8n_storage:/var/lib/postgresql/data
    ports:
      - "${N8N_POSTGRES_PORT}:${N8N_POSTGRES_PORT}"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${N8N_POSTGRES_USER} -d ${N8N_POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - ./n8n/backup:/backup

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - /Users/dan/workspace/file_share:/files
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - N8N_DISABLE_X_FRAME_OPTIONS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks: ['shared-network']
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  redis:
    image: "redis:alpine"
    networks: ['shared-network']
    ports:
      - "6379:6379"

networks:
  shared-network:
    external: true

volumes:
  postgres_n8n_storage:
  qdrant_storage:
  n8n_storage: